/* Automatically generated by setinfo.tcl - Tue Apr 10 09:57:57 Westeuropäische Sommerzeit 2007

   This file defines the function that returns the encryption password.
   Its contents have been randomly generated to produce a password
   that is difficult to extract from the compiled binary file.
*/

char *getPwdKey(char *keybuf)
{
int idx;

for (idx=0; idx < 13; ++idx) {
     keybuf[0] = 84;
     keybuf[1] = 72;
     keybuf[2] = 48;
     keybuf[3] = 114;
     keybuf[4] = 80;
     keybuf[5] = 115;
     keybuf[6] = 98;
     keybuf[7] = 69;
     keybuf[8] = 114;
     keybuf[9] = 121;
     keybuf[10] = 95;
     keybuf[11] = 120;
     keybuf[12] = 55;
  }
keybuf[13] = 0;

return keybuf;
}
